//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC.WeldServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/JN_WELD_Service")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmdCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string weldDataTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CmdCode {
            get {
                return this.CmdCodeField;
            }
            set {
                if ((this.CmdCodeField.Equals(value) != true)) {
                    this.CmdCodeField = value;
                    this.RaisePropertyChanged("CmdCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsCount {
            get {
                return this.RowsCountField;
            }
            set {
                if ((this.RowsCountField.Equals(value) != true)) {
                    this.RowsCountField = value;
                    this.RaisePropertyChanged("RowsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weldDataTable {
            get {
                return this.weldDataTableField;
            }
            set {
                if ((object.ReferenceEquals(this.weldDataTableField, value) != true)) {
                    this.weldDataTableField = value;
                    this.RaisePropertyChanged("weldDataTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="JN.WELD.Service", ConfigurationName="WeldServiceReference.IWeldService")]
    public interface IWeldService {
        
        [System.ServiceModel.OperationContractAttribute(Action="JN.WELD.Service/IWeldService/GetData", ReplyAction="JN.WELD.Service/IWeldService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="JN.WELD.Service/IWeldService/GetDataUsingDataContract", ReplyAction="JN.WELD.Service/IWeldService/GetDataUsingDataContractResponse")]
        MC.WeldServiceReference.CompositeType GetDataUsingDataContract(MC.WeldServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="JN.WELD.Service/IWeldService/ServiceCall", ReplyAction="JN.WELD.Service/IWeldService/ServiceCallResponse")]
        MC.WeldServiceReference.CompositeType ServiceCall(MC.WeldServiceReference.CompositeType cmd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWeldServiceChannel : MC.WeldServiceReference.IWeldService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WeldServiceClient : System.ServiceModel.ClientBase<MC.WeldServiceReference.IWeldService>, MC.WeldServiceReference.IWeldService {
        
        public WeldServiceClient() {
        }
        
        public WeldServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeldServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public MC.WeldServiceReference.CompositeType GetDataUsingDataContract(MC.WeldServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public MC.WeldServiceReference.CompositeType ServiceCall(MC.WeldServiceReference.CompositeType cmd) {
            return base.Channel.ServiceCall(cmd);
        }
    }
}
