//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JN_WELD_Service.OTCweldService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.ps.com", ConfigurationName="OTCweldService.SetCardPortType")]
    public interface SetCardPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getMeterData(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string CurrData(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SendWpsById(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getChargeRecord(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SendWps(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string CurrDataById(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getWpsById(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string setChargeInfo(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string SendWpsByManchineId(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getUserData(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getPriceData(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string setCardInfo(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string aa();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string example(string in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SetCardPortTypeChannel : JN_WELD_Service.OTCweldService.SetCardPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SetCardPortTypeClient : System.ServiceModel.ClientBase<JN_WELD_Service.OTCweldService.SetCardPortType>, JN_WELD_Service.OTCweldService.SetCardPortType {
        
        public SetCardPortTypeClient() {
        }
        
        public SetCardPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SetCardPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SetCardPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SetCardPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getMeterData(string in0) {
            return base.Channel.getMeterData(in0);
        }
        
        public string CurrData(string in0) {
            return base.Channel.CurrData(in0);
        }
        
        public string SendWpsById(string in0) {
            return base.Channel.SendWpsById(in0);
        }
        
        public string getChargeRecord(string in0) {
            return base.Channel.getChargeRecord(in0);
        }
        
        public string SendWps(string in0) {
            return base.Channel.SendWps(in0);
        }
        
        public string CurrDataById(string in0) {
            return base.Channel.CurrDataById(in0);
        }
        
        public string getWpsById(string in0) {
            return base.Channel.getWpsById(in0);
        }
        
        public string setChargeInfo(string in0) {
            return base.Channel.setChargeInfo(in0);
        }
        
        public string SendWpsByManchineId(string in0) {
            return base.Channel.SendWpsByManchineId(in0);
        }
        
        public string getUserData(string in0) {
            return base.Channel.getUserData(in0);
        }
        
        public string getPriceData(string in0) {
            return base.Channel.getPriceData(in0);
        }
        
        public string setCardInfo(string in0) {
            return base.Channel.setCardInfo(in0);
        }
        
        public string aa() {
            return base.Channel.aa();
        }
        
        public string example(string in0) {
            return base.Channel.example(in0);
        }
    }
}
